### ISSUE TITLE
Remove silence tracks

### ISSUE THREAD

**Issue by p1timmy** [chfoo/pbrchase#1]
Any tracks that don't have any narration (or transcription in track listing CSV file) should be removed, they're useless for soundboards. They include the following tracks:

```
ba040_1
ba110_0
ba360_0
ba360_1
ba360_2
eb_390
eb_450
h2b_230
la190_0
la310_0
tb_020m_2
tb_022m_2
tl_501
tl_503
```

**Comment by chfoo** [comment]
Thank you for the suggestion.
