### ISSUE TITLE
various edits and typos

### ISSUE THREAD

**Issue by joecabrera** [chfoo/pbrchase#3]
Some of these edits may be optional, so it's up to you to decide which changes to make. List sorted by file name, with correct text after the colon, and the explanation of the change in square brackets:

ba290_0:  The Colosseum battle is now at its final stage. A stronger opponent is going to appear. [second sentence missing]
ba320_0:  The League Battle at the Magma Colosseum is in its final match. [Magma missing]
bb050_0:  They're ready to battle and are awaiting their trainers' orders. [trainers', not trainer's]
bb060_0:  Both corners are so full of energy that there's no doubt this'll be a great battle. [this'll, not this will]
bb120_0:  The sight of Pokémon battling against a beautiful sunset, it's truly moving. [truly, not truely]
bb158_0:  Millions of stars flicker in the night as we stand on this meteorite. An exciting battle is about to begin in a world of illusion created by the Pokétopia Master. [night, not light]
bb164_0:  Thousands have gathered at this Colosseum located on the Main Street of Pokétopia to witness the big battle that is about to unfold. [this, not that]
cb_060:  It seems that its physical condition is not so good. [that missing]
cb_093:  The fourth set of Pokémon have appeared. [fourth, not forth]
eb_130:  The Blue Corner lost an important first fight. [remove has]
eb_294:  It's been nothing but draws so far for the Blue Corner. [so far missing]
eb_500-530:  The Challenger has won ... [8 entries all missing has]
eb_552:  The Pokétopia Master was too strong an opponent. [wrong text]
h1b_022:  Ohh! [wrong word]
h1b_023:  Ahh! [misspelled word]
h1b_070:  A huge amount of damage. It's down. [missing period]
h1b_130:  But its teammate was caught up in it too. [its, not it's]
h1b_130:  But its teammate was caught up in it too. [was, not is]
h1b_160:  Oh, the attacker is caught in the aftermath. [lowercase aftermath]
h1b_170:  It was an amazing attack, sacrificing itself like that, but it was the only one who went down. [add commas]
h1b_190:  What's that about? The battle's just started and a Pokémon is being beaten up by its own teammate? [battle's, not battle]
h1b_200 and h1b_200m have their text swapped
h1b_240m:  went down but it left a parting gift. [missing it]
h1l_020_0:  That just goes to show ya. You never know what'll happen at a Pokémon battle. [You, not You'll]
h1l_250:  Its final wish has been passed to the next Pokémon. [final wish - no caps]
h2b_040:  Its dry skin couldn't withstand the strong sunlight. Now, it's all dried out. [its, not it's]
h2b_070:  It's down due to damage from poison. [remove the]
kb_010:  had its wish come true and recovered health [had, not has]
kb_110:  recovered from its status problem with the help of an item [missing the]
kb_110:  recovered from its status problem with the help of an item [the missing]
la040_0:  This elegant and colorful Colosseum is filled with excitement. [missing period]
la092_0:  The courtyard of this peaceful castle is about to become an all-out battlefield. [add hyphen]
sb_100m:  has already been burned and the battle is just beginning [beginning misspelled]
sb_110:  Pokémon are already suffering from status problems, one after another, in this sudden and intense battle. [another misspelled]
sb_180:  That was an unexpected turn of events. [That, not The]
sb_190:  The battle's outcome is still up in the air. Who will reach for victory first? [missing for]
sb_210:  Both corners are carefully examining their opponent. [opponent misspelled]
sb_280m:  evened up the amount of remaining Pokémon despite being at an disadvantage [a, not an]
sb_400 and sb_400r have their text swapped
sb_560:  The mood in the Colosseum has become somewhat unsettling. [missing period]
sl_030:  Can they find a way out of this predicament? [missing ?]
sl_070:  That's gonna be trouble if this becomes a drawn-out battle. [gonna, not going to]
sl_120:  It's a mental tug-of-war as they anticipate each other's move. [other's, not others']
sl_160:  The battle has taken a U-turn. [capitalize U-turn]
sl_250:  They're gonna need to find a way out of this. [gonna, not going to]
tb_250:  An intense attack is launched with the helping hand of another Pokémon. [no hyphen]
tb_380m:  can't move due to a previously used attack [due missing]
tb_381:  can't move due to a previously used attack [due missing]
tb_382:  can't move due to a previously used attack [due missing]
tb_450:  Oh no. It attacked itself. [no hyphen]
tb_480m:  restored its health and feels the relief [missing last 4 words]
tb_552:  Its attack missed. [its, not it's]
tb_640:  Oh no, it soaked up the Liquid Ooze. [no hyphen in Oh no]
tb_845:  Brr. It was frozen solid. [Brr misspelled]
tb_951:  Bam! [wrong word]
wz_243k:  Mirror Coat echoes back. [echoes, not echos]
wz_323k:  Drenched by Water Spout. [Spout, not Sprout]
wz_449k:  Judgment has been dealt. [Judgment, not Judgement]
xb_110:  It's at two wins and two losses. A breathtakingly close fight. [at, not a]

Global:
"Strong Sunlight" should be lowercase, as "rain" is
"the challenger" should be "the Challenger"
"status" should be lowercase

**Comment by chfoo** [comment]
Big thanks for the edits! I took all of them except for h1b_200m/h1b_200 and sb_400r/sb_400. Are they actually swapped?

**Comment by joecabrera** [comment]
Yes, but I don't mean their labels; I mean what the announcer says in each one. 

Also, did you do all the original transcription? Most of the stuff I found was minor, but I'm really impressed at what a great job you did. (Also that someone even bothered to do so. I loved PBR so it was great finding this.)

**Comment by chfoo** [comment]
Yes, I did all the transcription myself. I'm trying hard but I still don't hear any wrong with h1b_200m and sb_400r though

**Comment by joecabrera** [comment]
I just listened again and you're right; those files I said to swap sound correct. (I was wrong about eb_500-530 too; I think I meant to remove "has" rather than insert it.) I guess my notes were a little off. Sorry about that!
